export interface ItineraryChoiceInfo {
  primaryNote: string;
  alternative: {
    title: string;
    detail: string;
    maps: string;
    note: string;
  };
}

function alt(
  primaryNote: string,
  title: string,
  detail: string,
  maps: string,
  note: string,
): ItineraryChoiceInfo {
  return {
    primaryNote,
    alternative: {
      title,
      detail,
      maps,
      note,
    },
  };
}

export const itineraryChoiceMap: Record<string, ItineraryChoiceInfo> = {
  "d1-0": alt(
    "Aggiornato Feb 2026: Suica mobile e ATM 7-Eleven restano la combinazione piu semplice per atterrare e partire subito senza perdere tempo in aeroporto.",
    "Tokyo Station / Ginza easy start",
    "Se l'arrivo e piu pesante del previsto, facciamo una versione soft: deposito bagagli, snack a <b>Tokyo Station</b>, primo giro a <b>Ginza</b> o <b>Marunouchi</b> e poi check-in presto. Meno cambi, meno stress, primo impatto comunque forte.",
    "https://www.google.com/maps/search/?api=1&query=Tokyo+Station",
    "Aggiornato Feb 2026: ottima alternativa se il volo atterra tardi o con meteo brutto; Tokyo Station resta il nodo piu pratico per riprendere il controllo del viaggio.",
  ),
  "d1-1": alt(
    "Aggiornato Feb 2026: Asakusa resta una prima tappa fortissima, ma nel pomeriggio si affolla velocemente; conviene farla solo se avete ancora energia vera.",
    "Yanaka Ginza + Nezu Shrine",
    "Versione piu rilassata e meno turistica del primo impatto a Tokyo. <b>Yanaka Ginza</b> ha atmosfera di quartiere, street snack e vibe retro; <b>Nezu Shrine</b> aggiunge torii, silenzio e foto forti senza il pienone di Asakusa.",
    "https://www.google.com/maps/search/?api=1&query=Yanaka+Ginza+Tokyo",
    "Aggiornato Feb 2026: alternativa ottima per jet lag o pioggia leggera, con meno folla e spostamenti piu facili rispetto al blocco Asakusa completo.",
  ),
  "d1-2": alt(
    "Aggiornato Feb 2026: la passeggiata lungo il Sumida funziona ancora bene come decompressione, soprattutto verso golden hour o con primi sakura a fine marzo.",
    "Tokyo Skytree Town + Solamachi",
    "Se fa freddo, tira vento o siete cotti, spostiamo la camminata dentro e attorno a <b>Tokyo Skytree Town</b>: vista della torre, food hall, souvenir e riparo rapido. Meno poetico, ma piu facile da gestire.",
    "https://www.google.com/maps/search/?api=1&query=Tokyo+Skytree+Town",
    "Aggiornato Feb 2026: piano B utile in caso di meteo instabile; resta vicino ad Asakusa e vi evita un blocco all'aperto lungo il fiume.",
  ),
  "d1-3": alt(
    "Aggiornato Feb 2026: Omoide Yokocho e Golden Gai restano iconici, ma cash, cover charge e file continuano a essere la norma nelle sere piu richieste.",
    "Kabukicho Tower + Shinjuku bar hop morbido",
    "Se non volete gestire cover e micro-bar pieni, fate una prima notte piu semplice: <b>Kabukicho Tower</b> per food hall e luci, poi 1-2 bar a Shinjuku senza l'ansia di Golden Gai. Stessa zona, meno attrito.",
    "https://www.google.com/maps/search/?api=1&query=Kabukicho+Tower",
    "Aggiornato Feb 2026: alternativa pratica se atterrate stanchi o se piove; vi tiene a Shinjuku con meno probabilita di sbattere contro bar full.",
  ),
  "d2-0": alt(
    "Aggiornato Feb 2026: Meiji Jingu continua a essere la miglior apertura di giornata in quell'area, soprattutto prima delle 10.",
    "Yoyogi Park + Omotesando stroll",
    "Se preferite meno rituale e piu respiro, fate <b>Yoyogi Park</b> e poi scendete su <b>Omotesando</b>. Verde, caffe migliori e transizione naturale verso Harajuku/Shibuya.",
    "https://www.google.com/maps/search/?api=1&query=Yoyogi+Park+Tokyo",
    "Aggiornato Feb 2026: buona alternativa se volete una mattina piu leggera o arrivate al Day 2 ancora un po' lenti.",
  ),
  "d2-1": alt(
    "Aggiornato Feb 2026: Cat Street resta piu interessante di Takeshita per un gruppo adulto; il quartiere cambia veloce ma l'asse Harajuku-Omotesando e ancora fortissimo.",
    "Omotesando + Aoyama design walk",
    "Se volete alzare il livello e abbassare il caos, spostatevi su <b>Omotesando</b> e <b>Aoyama</b>: flagship store, architettura, caffe migliori e ritmo meno teenager.",
    "https://www.google.com/maps/search/?api=1&query=Omotesando+Tokyo",
    "Aggiornato Feb 2026: alternativa piu elegante e piu comoda in caso di sabato/domenica affollati a Harajuku.",
  ),
  "d2-2": alt(
    "Aggiornato Feb 2026: SHIBUYA SKY resta aperto 10:00-22:30 con ingresso finale 21:20 e l'area continua a richiedere ticket timed entry; gli slot tramonto restano i piu sensibili.",
    "Tokyo Metropolitan Government Building observatory",
    "Se SHIBUYA SKY e sold out, meteo brutto o budget piu stretto, salite al <b>Tokyo Metropolitan Government Building</b> a Shinjuku: osservatorio gratuito a 202 m, ottima vista e accesso semplice.",
    "https://www.google.com/maps/search/?api=1&query=Tokyo+Metropolitan+Government+Building",
    "Aggiornato Feb 2026: GO TOKYO lo segnala ancora gratuito e aperto 9:30-22:00, ma con giorni di chiusura diversi tra North e South Observatory, quindi va controllato il giorno stesso.",
  ),
  "d2-3": alt(
    "Aggiornato Feb 2026: The SG Club resta una scelta alta, ma nelle fasce serali forti la prenotazione continua a fare la differenza.",
    "The Bellwood",
    "Cocktail molto forte e atmosfera Shibuya piu raccolta. <b>The Bellwood</b> e un piano B credibile se SG e pieno o se volete stare nello stesso quadrante senza rincorrere prenotazioni impossibili.",
    "https://www.google.com/maps/search/?api=1&query=The+Bellwood+Shibuya",
    "Aggiornato Feb 2026: alternativa utile quando SG Club e full o volete un bar d'autore con approccio un filo meno 'destination bar'.",
  ),
  "d2-4": alt(
    "Aggiornato Feb 2026: il karaoke privato resta facilissimo da fare in Shibuya, ma i pacchetti serali salgono parecchio nei weekend.",
    "Round1 Stadium Shibuya",
    "Se volete una notte piu mista di solo karaoke, fate <b>Round1 Stadium</b>: arcade, bowling, giochi assurdi e slot karaoke. Perfetto per tenere energia senza impegnarsi su 2 ore chiuse in stanza.",
    "https://www.google.com/maps/search/?api=1&query=Round1+Shibuya",
    "Aggiornato Feb 2026: buon piano B se i karaoke migliori hanno attesa o se il gruppo vuole una serata piu varia.",
  ),
  "d3-0": alt(
    "Aggiornato Feb 2026: teamLab Planets continua a usare ticket ufficiali a orario; il QR arriva prima dell'ingresso e il prezzo resta dinamico.",
    "teamLab Borderless Azabudai Hills",
    "Se preferite esperienza piu ampia e meno 'acqua fino alle ginocchia', passate a <b>teamLab Borderless</b> ad Azabudai Hills. E piu libero, piu grande, meno lineare e molto forte come piano B cittadino.",
    "https://www.google.com/maps/search/?api=1&query=teamLab+Borderless+Azabudai+Hills",
    "Aggiornato Feb 2026: il sito ufficiale indica Borderless aperto 8:30-21:00, ultimo ingresso un'ora prima; ticket dinamici e disponibilita ancora sensibile nei giorni forti.",
  ),
  "d3-1": alt(
    "Aggiornato Feb 2026: Tsukiji resta piu immediato di Toyosu per street food e flessibilita, soprattutto se volete zero prenotazioni.",
    "Toyosu Senkyaku Banrai",
    "Per un pranzo piu ordinato e comodo dopo teamLab, andate a <b>Senkyaku Banrai</b> a Toyosu: food hall, bagno, flusso semplice e meno dispersione rispetto al mercato aperto.",
    "https://www.google.com/maps/search/?api=1&query=Toyosu+Senkyaku+Banrai",
    "Aggiornato Feb 2026: ottimo se il meteo e brutto o se volete mangiare bene senza trasformare il pranzo in caccia casuale.",
  ),
  "d3-2": alt(
    "Aggiornato Feb 2026: Odaiba resta valida, ma alcune persone la trovano dispersiva se hanno gia fatto teamLab e tanta Tokyo moderna.",
    "Azabudai Hills + Tokyo Tower area",
    "Taglio piu compatto: restate su <b>Azabudai Hills</b>, Tokyo Tower view points e quartiere Minato. Meno trasporti, giornata piu elegante, sempre Tokyo-futuro ma con meno spreco di tempo.",
    "https://www.google.com/maps/search/?api=1&query=Azabudai+Hills",
    "Aggiornato Feb 2026: alternativa forte se volete restare centrali dopo teamLab Borderless o se Odaiba vi sembra troppo diluita.",
  ),
  "d3-3": alt(
    "Aggiornato Feb 2026: BenFiddich resta prenotabile su TableCheck e continua a essere una delle serate piu delicate da bloccare a Tokyo.",
    "Bar High Five",
    "Se BenFiddich non si apre, andate su un classico assoluto: <b>Bar High Five</b> a Ginza. Servizio altissimo, cocktail su misura e esperienza molto piu affidabile lato accesso.",
    "https://www.google.com/maps/search/?api=1&query=Bar+High+Five+Tokyo",
    "Aggiornato Feb 2026: alternativa premium molto credibile quando BenFiddich e pieno; meno 'cult herb-lab', ma solidissima per una notte memorabile.",
  ),
  "d4-0": alt(
    "Aggiornato Feb 2026: il trasferimento per Nikko resta pratico via Tobu, ma l'intera giornata ha senso solo se partite davvero presto.",
    "Kamakura day trip",
    "Se volete una gita storica meno lunga e piu facile da leggere, fate <b>Kamakura</b>: Grande Buddha, templi, mare e giornata meno tirata logisticamente rispetto a Nikko.",
    "https://www.google.com/maps/search/?api=1&query=Kamakura+Station",
    "Aggiornato Feb 2026: piano B intelligente se siete stanchi o se il meteo verso le montagne rende Nikko meno appetibile.",
  ),
  "d4-1": alt(
    "Aggiornato Feb 2026: Toshogu resta il cuore di Nikko, ma richiede energia e attenzione ai tempi se volete vedere tutto senza correre.",
    "Rinno-ji + Taiyuin",
    "Se volete un blocco spirituale meno congestionato, spostate focus su <b>Rinno-ji</b> e <b>Taiyuin</b>. Sempre Nikko, ma con atmosfera piu raccolta e meno pressione da 'must-see'.",
    "https://www.google.com/maps/search/?api=1&query=Rinnoji+Temple+Nikko",
    "Aggiornato Feb 2026: buona alternativa interna a Nikko se Toshogu e troppo pieno o volete una visita piu contemplativa.",
  ),
  "d4-2": alt(
    "Aggiornato Feb 2026: pranzo yuba e foto allo Shinkyo restano la combinazione piu semplice per restare in zona templi senza complicare la giornata.",
    "Kanmangafuchi Abyss walk",
    "Se preferite piu natura e meno tavolo, fate snack rapido e poi andate al <b>Kanmangafuchi Abyss</b>: fila di statue Jizo lungo il fiume, percorso quieto e molto fotogenico.",
    "https://www.google.com/maps/search/?api=1&query=Kanmangafuchi+Abyss",
    "Aggiornato Feb 2026: alternativa perfetta se avete voglia di silenzio e camminata invece di un pranzo piu lungo vicino ai templi.",
  ),
  "d4-3": alt(
    "Aggiornato Feb 2026: Kegon Falls continua a essere la grande deviazione naturale, ma resta il primo pezzo da tagliare se la giornata si stringe.",
    "Rientro anticipato + Tokyo dinner night",
    "Se saltate la cascata, rientrate prima e trasformate la sera in un vero ultimo round Tokyo: <b>depachika food run</b>, izakaya o tonkatsu serio senza farvi distruggere dalla logistica.",
    "https://www.google.com/maps/search/?api=1&query=Tokyo+Station+Food+Hall",
    "Aggiornato Feb 2026: piano B pragmatico, spesso migliore del forzare Kegon con meteo brutto o poca energia residua.",
  ),
  "d5-0": alt(
    "Aggiornato Feb 2026: Ameyoko resta vivissimo e caotico, ma alcuni banchi cambiano in fretta e la qualita e discontinua.",
    "Kappabashi + Ueno stroll",
    "Per una mattina piu curiosa e meno rumorosa, fate <b>Kappabashi</b> per coltelli, ceramiche e finti cibi da vetrina, poi passeggiata a <b>Ueno</b>.",
    "https://www.google.com/maps/search/?api=1&query=Kappabashi+Dougu+Street",
    "Aggiornato Feb 2026: alternativa piu pulita se volete shopping utile e foto diverse dal solito mercato affollato.",
  ),
  "d5-1": alt(
    "Aggiornato Feb 2026: Akihabara resta l'esperienza nerd piu densa, ma per chi non e super gamer puo diventare ripetitiva dopo un paio d'ore.",
    "Nakano Broadway",
    "Se volete una versione piu compatta e cult, puntate a <b>Nakano Broadway</b>: retro, figure, manga e negozi strani, ma in ambiente piu raccolto e meno dispersivo.",
    "https://www.google.com/maps/search/?api=1&query=Nakano+Broadway",
    "Aggiornato Feb 2026: piano B molto valido se volete lo stesso mondo nerd senza il bombardamento totale di Akihabara.",
  ),
  "d5-2": alt(
    "Aggiornato Feb 2026: il blocco libero a Tokyo resta utile proprio per assorbire ritardi, stanchezza o un ritorno in un quartiere amato.",
    "Shimokitazawa chill afternoon",
    "Vintage, caffe, piccoli negozi e ritmo rilassato. <b>Shimokitazawa</b> funziona benissimo come ultimo pomeriggio Tokyo se volete decomprimere prima della cena importante.",
    "https://www.google.com/maps/search/?api=1&query=Shimokitazawa+Tokyo",
    "Aggiornato Feb 2026: alternativa forte per un gruppo che non vuole piu macinare mega-attrazioni e preferisce vibes e shopping leggero.",
  ),
  "d5-3": alt(
    "Aggiornato Feb 2026: l'omakase resta uno dei blocchi che richiede piu conferme anticipatamente; i posti migliori continuano a sparire in fretta.",
    "Tempura or yakitori counter dinner",
    "Se l'omakase non si incastra, fate una cena ugualmente alta ma piu prenotabile: <b>tempura al bancone</b> o <b>yakitori omakase</b>. Meno pressione e comunque esperienza forte da Tokyo.",
    "https://www.google.com/maps/search/?api=1&query=Tempura+counter+Tokyo",
    "Aggiornato Feb 2026: piano B realistico quando il sushi top non si apre o i prezzi salgono troppo; esperienza premium senza inseguire solo sushi.",
  ),
  "d6-0": alt(
    "Aggiornato Feb 2026: Romancecar e Free Pass restano la soluzione piu lineare per Hakone; il punto vero e partire presto o la giornata si accorcia subito.",
    "Shinkansen to Odawara + direct Hakone base",
    "Se non volete dipendere dagli orari Odakyu, fate <b>Shinkansen fino a Odawara</b> e poi proseguite su Hakone. Costa di piu ma accorcia il viaggio e vi da piu controllo.",
    "https://www.google.com/maps/search/?api=1&query=Odawara+Station",
    "Aggiornato Feb 2026: alternativa utile se partite da una zona non comoda per Shinjuku o volete salvare tempo nella mattina.",
  ),
  "d6-1": alt(
    "Aggiornato Feb 2026: il loop completo resta iconico ma continua a dipendere da meteo, vento e visibilita del Fuji; e il primo blocco che va alleggerito se il cielo non collabora.",
    "Hakone Open-Air Museum + POLA Museum",
    "Se la funivia o il meteo non convincono, fate giornata culturale: <b>Hakone Open-Air Museum</b> e poi <b>POLA Museum of Art</b>. Meno foto da cartolina, ma giornata molto piu robusta.",
    "https://www.google.com/maps/search/?api=1&query=Hakone+Open+Air+Museum",
    "Aggiornato Feb 2026: l'Open-Air Museum continua a girare su fascia 9:00-17:00 e il sito segnala anche orari invernali specifici per i punti ristoro fino a fine febbraio, segno che conviene controllare i dettagli stagionali.",
  ),
  "d6-2": alt(
    "Aggiornato Feb 2026: ryokan + onsen restano il cuore di Hakone; se il tattoo policy crea dubbi, il bagno privato continua a essere la soluzione piu sicura.",
    "Hakone Yuryo private bath day-use + hotel stay",
    "Se il ryokan giusto non si trova o costa troppo, fate <b>Hakone Yuryo</b> con bagno privato prenotato e dormite in hotel normale. Perdete un po' di magia, ma salvate l'onsen in modo pulito.",
    "https://www.google.com/maps/search/?api=1&query=Hakone+Yuryo",
    "Aggiornato Feb 2026: il sito inglese conferma 19 private rooms e prenotazione del bagno privato fino a un mese prima; ottimo piano B se il ryokan premium non si incastra.",
  ),
  "d7-0": alt(
    "Aggiornato Feb 2026: Fushimi Inari all'alba resta una delle scelte piu forti dell'intero viaggio, soprattutto per evitare l'overcrowding delle ore centrali.",
    "Kyoto arrival + Higashiyama slow start",
    "Se il trasferimento da Hakone vi sballa gli orari, saltate l'alba e aprite Kyoto con <b>Higashiyama</b>, Ninenzaka, Sannenzaka e caffe con vista. Meno epico, molto piu realistico.",
    "https://www.google.com/maps/search/?api=1&query=Higashiyama+Kyoto",
    "Aggiornato Feb 2026: piano B pensato per il caso piu comune, cioe arrivo meno rapido del previsto e zero voglia di forzare un'alba scomposta.",
  ),
  "d7-1": alt(
    "Aggiornato Feb 2026: Nishiki resta divertente, ma la componente food-tourist e alta e il meglio si sente di piu quando non e strapieno.",
    "Kyoto station lunch + depachika",
    "Se volete mangiare bene senza folla compressa, fate pranzo dentro <b>Kyoto Station</b> o nei depachika. Meno fascino, ma molto piu efficienza e sedute vere.",
    "https://www.google.com/maps/search/?api=1&query=Kyoto+Station",
    "Aggiornato Feb 2026: alternativa utile nei giorni di pioggia o se il gruppo inizia a saturarsi di mercati coperti.",
  ),
  "d7-2": alt(
    "Aggiornato Feb 2026: Kinkaku-ji resta una tappa fotografica fortissima, ma e anche una delle visite piu veloci e piu da 'foto e via'.",
    "Nijo Castle",
    "Se preferite una visita piu articolata, puntate su <b>Nijo Castle</b>: storia vera, ambienti interni, giardini e tempo speso meglio di un singolo viewpoint.",
    "https://www.google.com/maps/search/?api=1&query=Nijo+Castle",
    "Aggiornato Feb 2026: piano B ottimo se volete piu contenuto storico e meno esperienza 'cartolina'.",
  ),
  "d7-3": alt(
    "Aggiornato Feb 2026: Arashiyama resta splendida ma richiede parecchio tempo e puo esplodere di folla molto presto.",
    "Ginkaku-ji + northern Higashiyama",
    "Se volete evitare il grande sbattimento verso ovest, restate sul lato est con <b>Ginkaku-ji</b> e quartieri piu tranquilli di Higashiyama. Meno iconic-photo, piu equilibrio.",
    "https://www.google.com/maps/search/?api=1&query=Ginkakuji+Kyoto",
    "Aggiornato Feb 2026: alternativa molto sensata quando volete tenere Kyoto compatta e non passare mezza giornata in transito.",
  ),
  "d7-4": alt(
    "Aggiornato Feb 2026: Gion e Pontocho restano fortissimi, ma nelle sere giuste diventano piu 'camminata tra turisti' che atmosfera intima.",
    "Kiyamachi dinner strip",
    "Se Pontocho e troppo saturo, fate <b>Kiyamachi</b>: sempre centrale, piena di locali e molto piu facile per trovare tavolo senza prenotazione chirurgica.",
    "https://www.google.com/maps/search/?api=1&query=Kiyamachi+Kyoto",
    "Aggiornato Feb 2026: piano B semplice e pragmatico per salvare la serata senza passare 40 minuti a cercare posto a Pontocho.",
  ),
  "d8-0": alt(
    "Aggiornato Feb 2026: Kiyomizu-dera resta essenziale e il sito ufficiale ha gia pubblicato la special night viewing di primavera dal 27 marzo al 5 aprile 2026.",
    "Kodai-ji + Hokan-ji / Yasaka Pagoda area",
    "Se Kiyomizu e ingestibile o volete un taglio piu fotografico, fate <b>Kodai-ji</b>, le vie intorno a <b>Yasaka Pagoda</b> e Higashiyama sud. Atmosfera Kyoto piena, con meno attrito.",
    "https://www.google.com/maps/search/?api=1&query=Kodai-ji+Kyoto",
    "Aggiornato Feb 2026: ottima alternativa soprattutto tra tardo pomeriggio e sera, quando l'area attorno a Yasaka Pagoda rende molto e Kiyomizu puo essere gia saturo.",
  ),
  "d8-1": alt(
    "Aggiornato Feb 2026: il Philosopher's Path resta dipendente dalla fioritura; a fine marzo puo essere bellissimo oppure ancora solo parzialmente acceso.",
    "Nanzen-ji + Keage Incline",
    "Se volete una passeggiata piu forte anche senza piena fioritura, fate <b>Nanzen-ji</b> e <b>Keage Incline</b>. Piacevole, storica e molto solida a fine marzo.",
    "https://www.google.com/maps/search/?api=1&query=Nanzenji+Temple",
    "Aggiornato Feb 2026: piano B migliore quando i sakura sono ancora indietro o volete un percorso con piu architettura e meno aspettativa floreale.",
  ),
  "d8-2": alt(
    "Aggiornato Feb 2026: il pomeriggio libero a Kyoto resta il blocco piu flessibile per inserire degustazioni, shopping o un'esperienza prenotata.",
    "Kyoto Railway Museum or manga museum slot",
    "Se piove o siete stanchi di templi, cambiate completamente tono: <b>Kyoto Railway Museum</b> oppure <b>Kyoto International Manga Museum</b>. Meno poetico, ma molto piu leggibile con energia bassa.",
    "https://www.google.com/maps/search/?api=1&query=Kyoto+Railway+Museum",
    "Aggiornato Feb 2026: alternativa perfetta da tenere in tasca per meteo brutto o saturazione culturale dopo due giorni pieni di Kyoto classica.",
  ),
  "d8-3": alt(
    "Aggiornato Feb 2026: Kyoto resta piu forte di quanto sembri sui cocktail, ma tanti bar piccoli premiano chi va con timing ordinato.",
    "L'Escamoteur Bar",
    "Per una serata piu scenografica e facile da raccontare, puntate su <b>L'Escamoteur Bar</b>: atmosfera teatrale, cocktail creativi e identita molto Kyoto-night.",
    "https://www.google.com/maps/search/?api=1&query=L%27Escamoteur+Bar+Kyoto",
    "Aggiornato Feb 2026: piano B forte quando Bar K6 o Bees Knees non si incastrano; atmosfera piu particolare e perfetta per ultima notte Kyoto.",
  ),
  "d9-0": alt(
    "Aggiornato Feb 2026: il blocco culturale resta deliberatamente aperto, quindi ha senso scegliere in base a prenotazioni vere e livello di energia del gruppo.",
    "Uji half-day tea focus",
    "Se volete un'alternativa piu specifica e piu 'Kyoto area', fate <b>Uji</b>: matcha serio, Byodo-in e ritmo molto piu pulito rispetto a una cooking class improvvisata.",
    "https://www.google.com/maps/search/?api=1&query=Uji+Kyoto",
    "Aggiornato Feb 2026: ottimo piano B se le classi non convincono o volete una mattina fuori Kyoto ma senza sbattervi troppo.",
  ),
  "d9-1": alt(
    "Aggiornato Feb 2026: Kyoto-Osaka resta uno spostamento semplicissimo, quindi vale la pena usarlo per riposizionare la giornata a seconda del mattino.",
    "Local JR transfer + hotel reset in Osaka",
    "Se non avete fretta, fate il trasferimento su treno JR locale, check-in, doccia e ripartenza morbida. Costa poco stress e vi fa entrare meglio nel cambio di energia Osaka.",
    "https://www.google.com/maps/search/?api=1&query=Shin-Osaka+Station",
    "Aggiornato Feb 2026: piano B pragmatico se il mattino a Kyoto si allunga o non volete correre per un tratto che comunque resta breve.",
  ),
  "d9-2": alt(
    "Aggiornato Feb 2026: Dotonbori resta l'impatto piu forte di Osaka, ma la qualita street food nei punti piu famosi varia e le file possono mangiarsi la serata.",
    "Ura-Namba food crawl",
    "Se volete mangiare meglio e con meno caos turistico, fate <b>Ura-Namba</b>: izakaya, piccoli counter e serata piu locale a pochi minuti dal rumore grosso di Dotonbori.",
    "https://www.google.com/maps/search/?api=1&query=Ura+Namba+Osaka",
    "Aggiornato Feb 2026: piano B ottimo se Dotonbori e troppo piena o se volete una prima notte Osaka meno 'cartolina rumorosa'.",
  ),
  "d10-0": alt(
    "Aggiornato Feb 2026: Hiroshima-Miyajima resta una deviazione fortissima ma molto lunga; ha senso solo se il gruppo ha davvero voglia di giornata piena.",
    "Himeji Castle half-day",
    "Se volete un day trip importante ma piu gestibile, andate a <b>Himeji</b>: castello eccezionale, logistica semplice e rientro meno massacrante di Hiroshima.",
    "https://www.google.com/maps/search/?api=1&query=Himeji+Castle",
    "Aggiornato Feb 2026: alternativa molto concreta quando volete vedere qualcosa di grande fuori Osaka senza sacrificare tutta l'energia residua.",
  ),
  "d10-1": alt(
    "Aggiornato Feb 2026: Miyajima resta iconica, ma maree e tempi di spostamento continuano a rendere la seconda parte della giornata poco indulgente.",
    "Osaka Aquarium Kaiyukan + Tempozan",
    "Se saltate Hiroshima, trasformate il giorno in una Osaka piu spettacolare ma rilassata: <b>Kaiyukan</b>, ruota panoramica di <b>Tempozan</b> e baia. Giorno facile e riuscito.",
    "https://www.google.com/maps/search/?api=1&query=Osaka+Aquarium+Kaiyukan",
    "Aggiornato Feb 2026: piano B forte per gruppo stanco o meteo incerto; grande attrazione, poco attrito logistico, e resta una giornata che si ricorda.",
  ),
  "d10-2": alt(
    "Aggiornato Feb 2026: l'opzione Osaka chill resta sensata dopo dieci giorni, soprattutto se volete lasciare benzina per Nara e USJ.",
    "Nakanoshima + Umeda slow city day",
    "Per un taglio meno turistico-commerciale, fate <b>Nakanoshima</b>, caffe, museo o passeggiata e poi <b>Umeda</b> al tramonto. Osaka piu adulta, meno lista-attrazioni.",
    "https://www.google.com/maps/search/?api=1&query=Nakanoshima+Osaka",
    "Aggiornato Feb 2026: alternativa ideale se non volete castello/market/shopping e preferite una giornata urbana piu pulita.",
  ),
  "d11-0": alt(
    "Aggiornato Feb 2026: il day trip a Nara resta semplicissimo da Osaka e continua a funzionare bene anche senza partire all'alba vera.",
    "Kobe half-day switch",
    "Se il gruppo non sente i cervi, passate a <b>Kobe</b>: waterfront, Kitano, carne e giornata urbana elegante a distanza breve da Osaka.",
    "https://www.google.com/maps/search/?api=1&query=Kobe+Sannomiya+Station",
    "Aggiornato Feb 2026: piano B per chi vuole cambiare completamente tono senza allungare troppo i tempi di trasporto.",
  ),
  "d11-1": alt(
    "Aggiornato Feb 2026: Todai-ji in inverno continua a stare su fascia 8:00-17:00 e il biglietto adulto e ancora 800 yen sul sito ufficiale.",
    "Nigatsudo + Isuien Garden",
    "Se volete evitare la massa attorno al Daibutsu, fate <b>Nigatsudo</b> per vista e atmosfera, poi <b>Isuien Garden</b>. Nara piu elegante, meno circus da cracker per cervi.",
    "https://www.google.com/maps/search/?api=1&query=Nigatsudo+Temple+Nara",
    "Aggiornato Feb 2026: piano B ottimo se Todai-ji e troppo pieno o se preferite una Nara piu contemplativa e meno centrata sulla foto iconica.",
  ),
  "d11-2": alt(
    "Aggiornato Feb 2026: Kasuga Taisha continua a completare bene Nara Park, ma verso meta giornata la stanchezza comincia spesso a farsi sentire.",
    "Naramachi old town lunch",
    "Tagliate il secondo blocco templare e scendete a <b>Naramachi</b>: strade storiche, pranzo tranquillo, botteghe e rientro piu umano verso Osaka.",
    "https://www.google.com/maps/search/?api=1&query=Naramachi+Nara",
    "Aggiornato Feb 2026: alternativa perfetta se il gruppo ha gia avuto abbastanza templi e vuole chiudere Nara con piu leggerezza.",
  ),
  "d11-3": alt(
    "Aggiornato Feb 2026: il pomeriggio morbido a Osaka prima di USJ resta una buona idea; sovraccaricare qui di solito si paga il giorno dopo.",
    "Spa reset + early dinner",
    "Se volete davvero proteggere USJ, fate <b>spa / sento</b> e cena presto invece di altro sightseeing. Zero glamour, massima efficacia.",
    "https://www.google.com/maps/search/?api=1&query=Spa+World+Osaka",
    "Aggiornato Feb 2026: piano B molto intelligente se sentite fatica vera nelle gambe o il meteo a Osaka non invoglia il pomeriggio all'aperto.",
  ),
  "d12-0": alt(
    "Aggiornato Feb 2026: USJ continua a richiedere strategia e l'assetto ticketing post-Expo e tornato circa a due mesi prima per le visite, con forte sensibilita su Express e slot area.",
    "Osaka Aquarium Kaiyukan + Tempozan day",
    "Se USJ diventa troppo caro, troppo pieno o semplicemente non vi convince, fate <b>Kaiyukan</b>, <b>Tempozan</b> e baia. Giornata blockbuster piu semplice, molto meno stressante.",
    "https://www.google.com/maps/search/?api=1&query=Osaka+Aquarium+Kaiyukan",
    "Aggiornato Feb 2026: piano B robusto se i biglietti USJ non si incastrano; perde adrenalina, ma guadagna tantissimo in tranquillita e prevedibilita.",
  ),
  "d12-1": alt(
    "Aggiornato Feb 2026: Super Nintendo World resta una delle aree piu richieste del parco e continua a premiare chi entra presto o ha Express con timed entry coerente.",
    "Universal Wonderland + Minion Park focus",
    "Se Nintendo e ingestibile, spostate il focus su aree meno tirate del parco: <b>Minion Park</b>, <b>Universal Wonderland</b> e attrazioni piu facili da concatenare.",
    "https://www.google.com/maps/search/?api=1&query=Minion+Park+USJ",
    "Aggiornato Feb 2026: alternativa interna a USJ utile quando SNW e full, il timed entry non si apre bene o volete proteggere il morale del gruppo.",
  ),
  "d12-2": alt(
    "Aggiornato Feb 2026: il blocco Harry Potter + Flying Dinosaur resta forte, ma e anche quello che si sgonfia di piu se le code vanno male.",
    "Cut queues, leave early, save the evening",
    "Se il parco inizia a trascinarvi, smettete di inseguire tutto: fate 1-2 ride ancora, souvenir rapidi e uscite prima. A Osaka potrete mangiare e recuperare molto meglio.",
    "https://www.google.com/maps/search/?api=1&query=Universal+Studios+Japan",
    "Aggiornato Feb 2026: piano B spesso migliore del testardirsi; a USJ il costo sunk non va inseguito se la giornata sta peggiorando.",
  ),
  "d12-3": alt(
    "Aggiornato Feb 2026: Shinsekai resta coerente dopo USJ, ma non e l'unica chiusura possibile se siete cotti.",
    "Namba easy dinner close to hotel",
    "Se il parco vi finisce, fate cena facile a <b>Namba</b> o vicino all'hotel. Meno folklore, piu probabilita di arrivare vivi all'ultimo giorno Osaka.",
    "https://www.google.com/maps/search/?api=1&query=Namba+Osaka",
    "Aggiornato Feb 2026: alternativa semplicemente migliore quando USJ ha gia preso tutto il carburante della giornata.",
  ),
  "d13-0": alt(
    "Aggiornato Feb 2026: Kuromon continua a essere forte al mattino, ma resta molto turistico e alcuni prezzi sono ormai da attrazione piu che da mercato locale.",
    "Fukutaro or sit-down brunch in Namba",
    "Se volete mangiare meglio e con meno confusione, fate brunch seduti in zona <b>Namba</b> e tenete Kuromon solo come passeggiata veloce o lo saltate del tutto.",
    "https://www.google.com/maps/search/?api=1&query=Namba+brunch+Osaka",
    "Aggiornato Feb 2026: piano B forte per ultimo giorno, quando pagare il caos da mercato puo avere meno senso del solito.",
  ),
  "d13-1": alt(
    "Aggiornato Feb 2026: Osaka Castle resta valido soprattutto per il parco e la stagione dei primi sakura, piu che per gli interni museali.",
    "Umeda Sky Building",
    "Se volete sostituire il blocco castello con vista urbana, andate su <b>Umeda Sky Building</b>. Meno passeggiata nel parco, piu skyline finale di Osaka.",
    "https://www.google.com/maps/search/?api=1&query=Umeda+Sky+Building",
    "Aggiornato Feb 2026: alternativa ottima se il meteo e grigio o se avete gia visto abbastanza castelli e preferite un finale piu contemporaneo.",
  ),
  "d13-2": alt(
    "Aggiornato Feb 2026: Amerikamura resta la scelta giovane e rumorosa, ma Orange Street continua a essere segnalata da Osaka Info come l'asse piu adulto e ricco di caffe e boutique.",
    "Orange Street + Nakazakicho",
    "Per l'ultimo shopping fate <b>Orange Street</b> e poi <b>Nakazakicho</b>: vintage, design, piccoli caffe e atmosfera molto piu piacevole di Amerikamura nelle ore centrali.",
    "https://www.google.com/maps/search/?api=1&query=Orange+Street+Osaka",
    "Aggiornato Feb 2026: piano B consigliato quasi sempre se volete un pomeriggio con piu gusto e meno casino gratuito.",
  ),
  "d13-3": alt(
    "Aggiornato Feb 2026: ultima sera Osaka funziona bene se lasciata elastica; forzare una mega-notte dopo USJ e ultimi giri puo essere controproducente.",
    "Hozenji + one good bar only",
    "Invece di chiudere con mille tappe, fate <b>Hozenji Yokocho</b>, una cena solida e <b>un solo cocktail bar</b>. Meno FOMO, miglior finale.",
    "https://www.google.com/maps/search/?api=1&query=Hozenji+Yokocho",
    "Aggiornato Feb 2026: alternativa piu adulta e spesso piu memorabile del tentare l'ultima maratona notturna per principio.",
  ),
  "d14-0": alt(
    "Aggiornato Feb 2026: per KIX il consiglio resta arrivare larghi; il margine in aeroporto vale piu di un'ultima attrazione improvvisata.",
    "Airport limousine bus option",
    "Se i treni non vi convincono o avete valigie pesanti, valutate il <b>limousine bus</b> per KIX da punti principali della citta. Meno figo, molto semplice.",
    "https://www.google.com/maps/search/?api=1&query=Kansai+International+Airport+bus",
    "Aggiornato Feb 2026: piano B logistico da tenere pronto se scioperi, bagagli o hotel position rendono i treni meno comodi del previsto.",
  ),
  "d14-1": alt(
    "Aggiornato Feb 2026: duty-free a KIX resta utile, ma non e il posto migliore per affidarsi all'ultimo whisky raro o a prezzi sempre convenienti.",
    "Buy in Namba before airport",
    "Se c'e qualcosa che volete davvero, compratelo a <b>Namba</b>, Donki o department store prima di partire e usate l'aeroporto solo per gli ultimi snack. Meno rischio di restare a mani vuote.",
    "https://www.google.com/maps/search/?api=1&query=Namba+Osaka+shopping",
    "Aggiornato Feb 2026: piano B consigliato per whisky, snack specifici o souvenir mirati; l'aeroporto va bene per l'ultimo colpo, non per contare sulla fortuna.",
  ),
};
